version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
